branch-defaults:
  master:
    environment: choice-env
    group_suffix: null
global:
  application_name: choicestarter
  branch: null
  default_ec2_keyname: choicestarter
  default_platform: Python 2.7
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: choicestarter
  repository: null
  sc: git
  workspace_type: Application
option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: server.py
